
package mdlph;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "MDLPH", targetNamespace = "http://server04/mdlph", wsdlLocation = "http://server04/holding/ws/mdlph.1cws?wsdl")
public class MDLPH
    extends Service
{

    private static final URL MDLPH_WSDL_LOCATION;
    private static final WebServiceException MDLPH_EXCEPTION;
    private static final QName MDLPH_QNAME = new QName("http://server04/mdlph", "MDLPH");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://server04/holding/ws/mdlph.1cws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDLPH_WSDL_LOCATION = url;
        MDLPH_EXCEPTION = e;
    }

    public MDLPH() {
        super(__getWsdlLocation(), MDLPH_QNAME);
    }

    public MDLPH(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDLPH_QNAME, features);
    }

    public MDLPH(URL wsdlLocation) {
        super(wsdlLocation, MDLPH_QNAME);
    }

    public MDLPH(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDLPH_QNAME, features);
    }

    public MDLPH(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDLPH(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDLPHPortType
     */
    @WebEndpoint(name = "MDLPHSoap")
    public MDLPHPortType getMDLPHSoap() {
        return super.getPort(new QName("http://server04/mdlph", "MDLPHSoap"), MDLPHPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDLPHPortType
     */
    @WebEndpoint(name = "MDLPHSoap")
    public MDLPHPortType getMDLPHSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://server04/mdlph", "MDLPHSoap"), MDLPHPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDLPH_EXCEPTION!= null) {
            throw MDLPH_EXCEPTION;
        }
        return MDLPH_WSDL_LOCATION;
    }

}
